#!/bin/bash

update_password()
{
    local host=192.168.18.131
    local old_pswd=skydata
    local new_pswd=skydata123
    local cmd0='curl -u "admin:OLD_PASSWORD" -X PUT -H "Content-Type: application/json" "http://HOST/api/users/1/password" -d dyh{"old_password": "OLD_PASSWORD", "new_password": "NEW_PASSWORD"}dyh'
    local cmd1=${cmd0//OLD_PASSWORD/${old_pswd}}
    local cmd2=${cmd1//NEW_PASSWORD/${new_pswd}}
    local cmd3=${cmd2//HOST/${host}}
    local cmd=${cmd3//dyh/\'}
    eval ${cmd} || {
        log_error "Failed to change admin password"
        return 1
    }
}

update_ui_admin_password()
{
    local old_password=skydata@1229
    local new_password=${HARBOR_UI_ADMIN_USER_PASSWD}
    local rst_code=$(curl -u "admin:${old_password}" -o /dev/null -s -w %{http_code} -X PUT -H "Content-Type: application/json" \
    "http://${ROCE_IP}:9980/api/users/1/password" -d "{\"old_password\":\"${old_password}\",\"new_password\":\"${new_password}\"}")
    [[ $rst_code -ne 200 ]] && {
        log_error "update harbor admin user password failed, result code is ${rst_code}"
        return 1
    }
    return 0
}

update_password
