#!/bin/bash

update_password()
{
    local host=192.168.18.131
    local old_pswd=skydata
    local new_pswd=skydata123
    local cmd0='curl -u "admin:OLD_PASSWORD" -X PUT -H "Content-Type: application/json" "http://HOST/api/users/1/password" -d dyh{"old_password": "OLD_PASSWORD", "new_password": "NEW_PASSWORD"}dyh'
    local cmd1=${cmd0//OLD_PASSWORD/${old_pswd}}
    local cmd2=${cmd1//NEW_PASSWORD/${new_pswd}}
    local cmd3=${cmd2//HOST/${host}}
    local cmd=${cmd3//dyh/\'}
    eval ${cmd} || {
        log_error "Failed to change admin password"
        return 1
    }
}

update_password
